### PR TITLE
Create skeleton of configs for docker compose with Jenkins build

### PR DESCRIPTION
**Pull request by JaroslavaJaskova**

### CODE REVIEW

**Comment by LukasOscipovsky** [comment]
From my point of view looks fine, is it always doing npm install for each build?

**Review by michalvankodev — COMMENTED** [review]
I will like to upgrade Node version to the latest 10.1 so we can use latest features and latest documentation

**Comment by JaroslavaJaskova** [comment]
@LukasOscipovsky , yes it is still doing the npm install. As I have read it's common approach as dependencies need to be loaded into container inside this way..The copying them from host to container is not safe..

**Comment by JaroslavaJaskova** [comment]
@michalvankodev ok, I will upgrade..

**Review by michalvankodev — APPROVED** [review]

**Pull request merged**
